const actionTypes = {
    ADD_POST: "ADD-POST",
    UPDATE_NEW_POST_TEXT : "UPDATE-NEW-POST-TEXT",
    SEND_MESSAGE: "SEND-MESSAGE",
    UPDATE_NEW_MESSAGE_TEXT: "UPDATE-NEW-MESSAGE-TEXT",
    SWITCH_FOLLOW: "SWITCH-FOLLOW",
    SET_USERS: "SET-USERS",
    REMOVE_USERS: "REMOVE-USERS",
    SET_USER: "SET-USER",
    REMOVE_USER: "REMOVE-USER",
};

export default actionTypes;