const actionTypes = {
    ADD_POST: "ADD-POST",
    UPDATE_NEW_POST_TEXT : "UPDATE-NEW-POST-TEXT",
    SEND_MESSAGE: "SEND-MESSAGE",
    UPDATE_NEW_MESSAGE_TEXT: "UPDATE-NEW-MESSAGE-TEXT",
};

export default actionTypes;